qst = ["What sort of trees are the oldest trees in the United States? ",
       "What is the longest river system in the world? ",
       "What is the largest river by discharge volume in the world? ",
       "What is the deepest lake in the world? ",
       "What is the largest lake in the world by surface area? ",
       "What larger sea is the Ionian Sea part of? ",
       "What is the tallest mountain in Africa? ",
       "What is the tallest mountain in South America? ",
       "What is the country with the largest number of lakes in the world? ",
       "What is the hottest desert in the world? ",
       "In what part of the world(in the present day) did camelids first appear? ",
       "What is the largest extant member of the marine dolphin family? ",
       "What is the animal that is a feline but also has canine behaviours? ",
       "What marsupial carnivore went extinct in 1936? ",
       "What was the geological period when the first flying mammals appeared? ",
       "What is a species of very large squid found only in the southern hemisphere? ",
       "Down to what depth does the bathypelagic zone of the open ocean extend to? ",
       "What other whale is the beluga whale known to interbreed with? ",
       "What is the second most dense planet in the Solar System? ",
       "What is the largest exposed crater on Mars called? ",
       "What is the most common element in Earth's atmosphere? ",
       "What is the densest stable metal on Earth? ",
       "What is the bird whose diet consists mostly of bone? ",
       "What is the most corrosion resistant metal known? ",
       "What forest has the largest diversity of dipterocarp trees? ",
       "Graphite is an allotrope of what element? ",
       "The largest bush in the world is of what plant? ",
       "What is the oldest landscape that has been measured on Earth? ",
       "What is the first plant whose fossils were found in Antarctica? ",
       "What is the most common sedimentary rock? "]

awe = [["bristlecone pines", "bristlecone pine", "bristlecone", "pines", "pine"],
       ["nile", "the nile", "nile river", "the nile river"],
       ["amazon", "the amazon", "amazon river", "the amazon river"],
       ["baikal", "lake baikal"], ["michigan-huron", "lake superior"],
       ["mediterranean sea", "the mediterranean sea", "mediteranean sea", "the mediteranean sea",
        "mediterranean", "mediteranean", "the mediterranean"], ["kilimanjaro", "mount kilimanjaro"], "aconcagua",
       "canada", ["lut", "lut desert", "the lut desert", "dasht-e lut", "dashte lut", "dasht e lut"],
       ["north america", "america"], ["orca", "orcas", "killer whale", "killer whales", "the orca"],
       ["hyena", "hyaena", "the hyena", "hyenas"], ["thylacine", "tasmanian tiger", "tasmanian wolf"],
       ["jurassic", "the jurassic", "jurasic", "the jurasic"], ["colossal squid", "collosal squid", 
       "colosal squid", "antarctic cranch squid"], ["4000m", "4.000m", "4,000m", "4km", "4 km", "4000",
       "4.000", "4,000", "4000 m", "4.000 m", "4,000 m", "13,000ft", "13000ft", "13000"],
       ["narwhal", "the narwhal", "narwal", "narhal"], "mercury", "hellas", 
       ["nitrogen", "azot", "azote", "n"], ["osmium", "os"],
       ["bearded vulture", "the bearded vulture", "lammergeier", "ossifrage", "bearded vultures"], ["iridium", "ir"],
       ["borneo", "borneo forest", "the borneo forest", "the borneo", "borneo rainforest", "borneo rain forest",
        "borneo lowland forest", "borneo rain forests", "borneo lowland rain forests"],
        ["carbon", "c"], ["rose","roses"], ["paran", "paran plains", "the paran plains", "the negev",
       "negev desert"], ["glossopteris", "glosopteris"], "shale"]